CREATE TABLE IF NOT EXISTS campus_summary_snapshots (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    snapshot_date DATE NOT NULL,
    campus_id INT NOT NULL,
    campus_name VARCHAR(100) NOT NULL,
    reservation_count INT NOT NULL DEFAULT 0,
    reservation_pending_count INT NOT NULL DEFAULT 0,
    reservation_approved_count INT NOT NULL DEFAULT 0,
    reservation_rejected_count INT NOT NULL DEFAULT 0,
    asset_request_count INT NOT NULL DEFAULT 0,
    asset_request_pending_count INT NOT NULL DEFAULT 0,
    asset_request_approved_count INT NOT NULL DEFAULT 0,
    asset_request_rejected_count INT NOT NULL DEFAULT 0,
    asset_item_count INT NOT NULL DEFAULT 0,
    asset_budget_total_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
    asset_budget_locked_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
    asset_budget_used_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
    asset_budget_available_amount DECIMAL(14, 2) NOT NULL DEFAULT 0,
    daily_report_count INT NOT NULL DEFAULT 0,
    daily_report_pending_count INT NOT NULL DEFAULT 0,
    daily_report_approved_count INT NOT NULL DEFAULT 0,
    daily_report_rejected_count INT NOT NULL DEFAULT 0,
    UNIQUE KEY uq_summary_snapshot_date_campus (snapshot_date, campus_id),
    KEY idx_summary_snapshot_date (snapshot_date),
    KEY idx_summary_snapshot_campus (campus_id)
);
